name: update site on ansible push

on:
  push:
    branches:
      - main
    paths:
      - ansible/**
      - data/**
      - latex/**

env:
    # in production better use an OIDC connection + pass `role-to-assume`
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  latex:
    name: Run pdflatex
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          # alt: package_file:
          packages: >
            latex latex-bin sourcesanspro moresize xcolor hyperref enumitem
            titlesec ec ly1 geometry pdftexcmds fancyhdr amsfonts xkeyval
            infwarerr kvoptions etoolbox

      - name: Run pdflatex
        run: |
          cd latex
          pdflatex resume.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: latex/resume.pdf
          if-no-files-found: error

  upload:
    name: Upload data to S3 with ansible
    runs-on: ubuntu-latest
    needs: latex

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      # - name: Copy fresh resume from latex dir
      #   run: |
      #     cp latex/resume.pdf data/pdfs/resume.pdf

      - name: Download built resume
        uses: actions/download-artifact@v4
        with:
          name: resume
          path: data/pdfs/

      - name: Install ansible with pip
        run: |
          sudo apt update
          sudo apt install pip git
          pip install ansible-core boto3

      - name: Run ansible
        run: |
          cd ansible
          ansible-galaxy collection install -r requirements.yml
          ansible-playbook -i localhost, -c local upload.yaml --diff
