name: build resume pdf from latex source

on:
  workflow_dispatch  # switch to manual run for now
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - latex/**

# env:

jobs:
  deploy:
    name: Run pdflatex
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          # alt: package_file:
          packages: >
            latex latex-bin sourcesanspro moresize xcolor hyperref enumitem
            titlesec ec ly1 geometry pdftexcmds fancyhdr amsfonts xkeyval
            infwarerr kvoptions etoolbox

      - name: Run pdflatex
        run: |
          cd latex
          pdflatex resume.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: latex/resume.pdf
          if-no-files-found: error
